ALTER TABLE users
    MODIFY COLUMN role ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER';

ALTER TABLE stores
    MODIFY COLUMN category ENUM('CONVENIENCE_STORE', 'CAFE', 'RESTAURANT', 'PHARMACY', 'OTHER') NOT NULL DEFAULT 'CONVENIENCE_STORE';
